### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by bobychaudhary**
README file added

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Why, what's the point of adding an empty file?

**Comment by bobychaudhary** [comment]
@lynxlynxlynx I was thinking an empty file is better than nothing, If you don't like I'm sorry

**Comment by lynxlynxlynx** [comment]
That's absurd. Besides, this is a mirror, so a wrong place to propose changes.

**Comment by bobychaudhary** [comment]
I'm sorry I'll never do this again

**Pull request closed without merging**
